# SPDX-FileCopyrightText: 2026 The Particles authors
#
# SPDX-License-Identifier: Apache-2.0

"""mkdocs build hook — the artifact host: serve the normative artifacts at their
canonical paths, and render the vocabulary as a human page.

Every published particle bakes its schema ``$id`` and its JSON-LD ``@context`` /
SHACL vocabulary IRIs in as ``https://linkedparticles.org/...``. A
deployed docs site is what makes those identifiers *dereference* (D1),
so the site build — not a hand-copied directory — is what puts the bytes there:

* ``on_pre_build`` writes ``docs/vocab.md`` from ``artifacts/schemas/context.jsonld``
  (gitignored, like ``stylesheets/tokens.css``), so the ``#``-fragment
  vocabulary namespace resolves to a themed, searchable page carrying a real
  anchor per term.
* ``on_pre_build`` also writes one page per **own-origin sub-namespace** the
  context declares (``extraction:``, ``social:``, ``hn:``, … at
  ``https://linkedparticles.org/vocab/<name>#``) into ``docs/vocab/<name>.md``
  (also gitignored). Published particles carry these IRIs, so each one must
  dereference just like the core vocabulary namespace; the pages are what serve
  them. External vocabularies the context maps onto (nomisma, schema.org,
  wikidata, …) dereference at their own hosts and are not our obligation.
* ``on_post_build`` copies ``artifacts/schemas/**`` into the built site under
  ``/schemas/…`` and asserts the copy is byte-identical.

The artifacts are deliberately **not** routed through ``docs/``: mkdocs would
copy a static file happily enough, but anything under ``docs/`` is fair game for
a future build step, and the normative bytes must not be. Copying into
``site_dir`` after the build makes byte-identity structural.

The hook also checks each schema's own ``$id`` against the path it is served at,
so a renamed artifact fails the build instead of silently publishing an
identifier that no longer dereferences. The check compares *paths only* — the
origin is whatever the artifacts themselves declare — so it holds in the
monorepo's own build and in the published one alike.

Media types belong to the serving layer, and one of them is not ours to choose.
GitHub Pages maps ``.jsonld`` to ``application/ld+json`` and ``.ttl`` to
``text/turtle`` (both verified against a live Pages host, 2026-08-17). ``.json``
arrives as ``application/json``, not the ``application/schema+json`` a JSON
Schema *may* also carry, and Pages has no media-type override. That is accepted:
``application/json`` is valid and universally parsed for a schema document, and
the dereference check accepts either, so a future move to a host that can send
the stricter type is not a breaking change. What must never change is the path —
the ``$id`` strings are permanent and already published.

Wired up via ``hooks:`` in ``mkdocs.yml``, and in the standard repo's own
``mkdocs.yml`` overlay, which the publication export lays into that tree.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

_REPO_ROOT = Path(__file__).resolve().parent.parent
_ARTIFACTS = _REPO_ROOT / "artifacts" / "schemas"
_DOCS = _REPO_ROOT / "docs"
_VOCAB_PAGE = _DOCS / "vocab.md"
# Own-origin sub-namespace pages are generated under here (one .md per
# ``…/vocab/<name>#`` prefix). The directory is generated wholesale each build,
# so it holds nothing but generated files and can be rebuilt from scratch.
_VOCAB_SUBNS_DIR = _DOCS / "vocab"

# The site path the artifacts are served under — the ``/schemas/…`` segment of
# every canonical ``$id``. Asserted against the artifacts rather than
# configured, so the served path and the published identifier cannot drift.
_SERVE_PREFIX = "schemas"

# The vocabulary namespace this page documents; every other declared prefix is
# an external vocabulary the context maps terms into.
_PRIMARY_PREFIX = "particles"

# The artifact whose ``$id`` fixes the canonical origin for every derived IRI
# (the SHACL shapes carry no ``$id`` of their own).
_ORIGIN_ANCHOR = "particle.schema.json"

_BANNER = (
    "<!-- GENERATED by hooks/copy_schema_artifacts.py from\n"
    "     artifacts/schemas/context.jsonld — do not edit by hand. -->"
)


# --------------------------------------------------------------------------- #
# Reading the context
# --------------------------------------------------------------------------- #
@dataclass
class Term:
    """One vocabulary term: an IRI, the JSON key(s) bound to it, its typing."""

    iri: str
    prefix: str
    local: str
    keys: list[str] = field(default_factory=list)
    typing: list[str] = field(default_factory=list)


@dataclass
class Vocabulary:
    """The context, sorted into the shapes the page renders."""

    prefixes: dict[str, str] = field(default_factory=dict)
    classes: list[Term] = field(default_factory=list)
    properties: list[Term] = field(default_factory=list)
    individuals: list[Term] = field(default_factory=list)
    external: list[Term] = field(default_factory=list)
    aliases: list[tuple[str, str]] = field(default_factory=list)


def _load_context() -> dict[str, Any]:
    """The ``@context`` mapping of the canonical JSON-LD context artifact."""
    src = _ARTIFACTS / "context.jsonld"
    if not src.exists():
        rel = src.relative_to(_REPO_ROOT)
        raise FileNotFoundError(f"{rel} missing — the normative artifacts are gone?")
    doc = json.loads(src.read_text(encoding="utf-8"))
    ctx = doc.get("@context")
    if not isinstance(ctx, dict):
        raise RuntimeError("artifacts/schemas/context.jsonld has no object-valued `@context`")
    return ctx


def _is_prefix_decl(value: object) -> bool:
    """True for a namespace declaration (``"particles": "https://…/vocab#"``)."""
    return isinstance(value, str) and "://" in value and value.endswith(("#", "/"))


def _split_curie(curie: str) -> tuple[str, str] | None:
    """``("particles", "content")`` for ``particles:content``; None if not a CURIE."""
    if ":" not in curie or curie.startswith("@") or "://" in curie:
        return None
    prefix, _, local = curie.partition(":")
    if not prefix or not local:
        return None
    return prefix, local


def parse_vocabulary(ctx: dict[str, Any]) -> Vocabulary:
    """Sort a JSON-LD ``@context`` into prefixes, classes, properties, individuals.

    The classification is purely structural, so a new term shows up on the page
    without anyone editing the page:

    * a string value that is an absolute IRI ending in ``#`` or ``/`` declares a
      **namespace prefix**;
    * a string value naming a JSON-LD keyword (``"id": "@id"``) is a
      **keyword alias**;
    * any other string value is a CURIE for a **class** (capitalized key) or an
      **individual** (all-caps key — the status and uncertainty enumerations);
    * an object value is a **property**, its ``@id`` giving the term and its
      ``@type`` / ``@container`` the JSON-LD typing.

    Terms are grouped by IRI, so the several JSON keys that share one term
    (``externalIds`` / ``externalRefs`` → ``particles:externalRef``) render as
    one row with one anchor.
    """
    vocab = Vocabulary()
    by_iri: dict[str, Term] = {}

    # Two passes: prefixes first, so a term declared above its own namespace
    # still expands (the context's ordering is not a contract).
    for key, value in ctx.items():
        if not key.startswith("@") and _is_prefix_decl(value):
            assert isinstance(value, str)
            vocab.prefixes[key] = value

    def term_for(curie: str) -> Term | None:
        parts = _split_curie(curie)
        if parts is None:
            return None
        prefix, local = parts
        base = vocab.prefixes.get(prefix)
        iri = f"{base}{local}" if base else curie
        existing = by_iri.get(iri)
        if existing is not None:
            return existing
        term = Term(iri=iri, prefix=prefix, local=local)
        by_iri[iri] = term
        return term

    for key, value in ctx.items():
        if key.startswith("@") or _is_prefix_decl(value):
            continue
        if isinstance(value, str):
            if value.startswith("@"):
                vocab.aliases.append((key, value))
                continue
            term = term_for(value)
            if term is None:
                continue
            term.keys.append(key)
            if term in vocab.classes or term in vocab.individuals or term in vocab.external:
                continue
            if key.isupper():
                vocab.individuals.append(term)
            elif key[:1].isupper():
                vocab.classes.append(term)
            else:
                vocab.properties.append(term)
            continue
        if isinstance(value, dict):
            at_id = value.get("@id")
            if not isinstance(at_id, str):
                continue
            term = term_for(at_id)
            if term is None:
                continue
            first_time = not term.keys
            term.keys.append(key)
            for facet in ("@type", "@container"):
                got = value.get(facet)
                if isinstance(got, str):
                    entry = f"`{facet}: {got}`"
                    if entry not in term.typing:
                        term.typing.append(entry)
            if first_time:
                if term.prefix == _PRIMARY_PREFIX:
                    vocab.properties.append(term)
                else:
                    vocab.external.append(term)

    return vocab


# --------------------------------------------------------------------------- #
# Canonical IRIs (derived from the artifacts, never configured)
# --------------------------------------------------------------------------- #
def canonical_origin() -> str:
    """The scheme + host every canonical identifier is published under.

    Taken from ``particle.schema.json``'s own ``$id`` so the site never invents
    an origin the artifacts do not already claim.
    """
    src = _ARTIFACTS / _ORIGIN_ANCHOR
    doc = json.loads(src.read_text(encoding="utf-8"))
    schema_id = doc.get("$id")
    if not isinstance(schema_id, str):
        raise RuntimeError(f"artifacts/schemas/{_ORIGIN_ANCHOR} has no string `$id`")
    parts = urlsplit(schema_id)
    if not parts.scheme or not parts.netloc:
        raise RuntimeError(f"artifacts/schemas/{_ORIGIN_ANCHOR} `$id` is not an absolute URL")
    return f"{parts.scheme}://{parts.netloc}"


def artifact_files() -> list[Path]:
    """Every normative artifact file, in stable order."""
    return sorted(p for p in _ARTIFACTS.rglob("*") if p.is_file())


def check_schema_ids() -> None:
    """Assert every schema's ``$id`` path matches the path it is served at.

    A rename that is not mirrored in the ``$id`` (or the reverse) publishes an
    identifier that does not dereference — the exact failure the artifact host
    exists to prevent — so it fails the build here rather than at deploy.
    """
    problems: list[str] = []
    for path in artifact_files():
        if path.suffix != ".json":
            continue
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:  # pragma: no cover - docs_check covers parse
            problems.append(f"{path.relative_to(_REPO_ROOT)}: invalid JSON ({exc})")
            continue
        schema_id = doc.get("$id")
        if not isinstance(schema_id, str):
            continue  # not a JSON Schema (similarity vectors and friends)
        want = f"/{_SERVE_PREFIX}/{path.relative_to(_ARTIFACTS).as_posix()}"
        got = urlsplit(schema_id).path
        if got != want:
            problems.append(
                f"{path.relative_to(_REPO_ROOT)}: `$id` path {got!r} != served path {want!r}"
            )
    if problems:
        raise RuntimeError(
            "artifact host: schema `$id` does not match the path it is served at:\n  "
            + "\n  ".join(problems)
        )


# --------------------------------------------------------------------------- #
# Own-origin sub-namespaces (derived from the context, never configured)
# --------------------------------------------------------------------------- #
@dataclass
class Subnamespace:
    """One own-origin vocabulary sub-namespace declared by the context.

    ``prefix`` / ``iri`` are the context declaration
    (``"extraction": "https://linkedparticles.org/vocab/extraction#"``);
    ``serve_path`` is the site path the ``#``-fragment IRIs dereference to
    (``/vocab/extraction``); ``doc_relpath`` is the ``docs/``-relative Markdown
    file that produces it (``vocab/extraction.md``).
    """

    prefix: str
    iri: str
    serve_path: str
    doc_relpath: str


def _terms_for_prefix(vocab: Vocabulary, prefix: str) -> list[Term]:
    """Every parsed term whose CURIE prefix is *prefix*, name-sorted."""
    out: list[Term] = []
    for group in (vocab.classes, vocab.properties, vocab.individuals, vocab.external):
        out.extend(t for t in group if t.prefix == prefix)
    return sorted(out, key=lambda t: t.local)


def subnamespaces(vocab: Vocabulary, origin: str) -> list[Subnamespace]:
    """The context's own-origin vocabulary sub-namespaces, in prefix order.

    A prefix under ``{origin}/vocab/`` (``…/vocab/extraction#``) names a term
    space this project is responsible for serving — published particles carry
    those IRIs, so each must dereference. The primary namespace
    (``…/vocab#`` → the ``/vocab`` page) and every external vocabulary
    (nomisma, schema.org, wikidata, …) are excluded: the first is the vocab
    page's job, the rest resolve at their own hosts.
    """
    prefix_root = f"{origin}/vocab/"
    out: list[Subnamespace] = []
    for prefix, iri in sorted(vocab.prefixes.items()):
        if not iri.startswith(prefix_root):
            continue
        serve_path = urlsplit(iri).path.rstrip("/")  # /vocab/extraction (drop the fragment's #)
        out.append(
            Subnamespace(
                prefix=prefix,
                iri=iri,
                serve_path=serve_path,
                doc_relpath=f"{serve_path.lstrip('/')}.md",
            )
        )
    return out


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def _anchor(local: str) -> str:
    """A term name carrying the ``#``-fragment anchor its IRI dereferences to."""
    return f"`{local}`{{ #{local} }}"


def _table(header: tuple[str, ...], rows: list[tuple[str, ...]]) -> list[str]:
    if not rows:
        return []
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    out.append("")
    return out


def _keys(term: Term) -> str:
    return ", ".join(f"`{k}`" for k in term.keys)


def render_vocab_page(vocab: Vocabulary, origin: str) -> str:
    """The Markdown source of the ``/vocab`` page."""
    ns = vocab.prefixes.get(_PRIMARY_PREFIX, f"{origin}/vocab#")
    lines = [
        _BANNER,
        "",
        "# Vocabulary",
        "",
        f"The Particles vocabulary namespace is `{ns}`.",
        "",
        "Every term below is a `#` fragment of this page: the JSON-LD `@context`",
        "and the SHACL shapes name terms as `particles:<term>`, which expands to",
        f"`{ns}<term>` and resolves here. The normative definitions live in the",
        "[technical specification](spec/technical-specification.md); this page is",
        "the dereferenceable index of the identifiers themselves.",
        "",
        '!!! note "Terms are stable; this page is generated"',
        "",
        "    This page is rendered at build time from the canonical",
        f"    [`context.jsonld`]({origin}/{_SERVE_PREFIX}/context.jsonld), so it",
        "    cannot drift from the artifact a consumer actually fetches.",
        "",
        "## Class terms",
        "",
        "The record types the schema defines.",
        "",
    ]
    lines += _table(
        ("Term", "JSON key", "IRI"),
        [(_anchor(t.local), _keys(t), f"`{t.iri}`") for t in vocab.classes],
    )
    lines += [
        "## Property terms",
        "",
        "Each row is one vocabulary term and the JSON key (or keys) that bind to",
        "it, with the JSON-LD typing the context declares.",
        "",
    ]
    lines += _table(
        ("Term", "JSON key", "JSON-LD typing"),
        [
            (_anchor(t.local), _keys(t), " ".join(t.typing) or "—")
            for t in sorted(vocab.properties, key=lambda t: t.local)
        ],
    )
    lines += [
        "## Individual terms",
        "",
        "The enumerated values — lifecycle status and PSUM uncertainty nature —",
        "carry IRIs of their own so a serialized particle names them by identifier",
        "rather than by string.",
        "",
    ]
    lines += _table(
        ("Term", "JSON key", "IRI"),
        [
            (
                _anchor(t.local) if t.prefix == _PRIMARY_PREFIX else f"`{t.local}`",
                _keys(t),
                f"`{t.iri}`",
            )
            for t in vocab.individuals
        ],
    )
    if vocab.external:
        lines += [
            "## Terms mapped into external vocabularies",
            "",
            "Where an established vocabulary already has the term, the context maps",
            "onto it instead of minting a Particles IRI. These identifiers",
            "dereference at their own hosts, not here.",
            "",
        ]
        lines += _table(
            ("JSON key", "IRI"),
            [(_keys(t), f"`{t.iri}`") for t in sorted(vocab.external, key=lambda t: t.local)],
        )
    if vocab.aliases:
        lines += [
            "## Keyword aliases",
            "",
        ]
        lines += _table(
            ("JSON key", "JSON-LD keyword"),
            [(f"`{k}`", f"`{v}`") for k, v in vocab.aliases],
        )
    lines += [
        "## Related namespaces",
        "",
        "Prefixes the context declares. The Particles ones under `…/vocab/` are",
        "extension-scoped: they namespace the domain-specific fields an extractor",
        "may attach, carry no terms in the core context, and each dereferences to",
        "its own page (linked below). Every other prefix maps onto an established",
        "external vocabulary that resolves at its own host.",
        "",
    ]
    subns_page = {sub.prefix: sub.doc_relpath for sub in subnamespaces(vocab, origin)}
    lines += _table(
        ("Prefix", "Namespace IRI"),
        [
            (
                f"[`{p}`]({subns_page[p]})" if p in subns_page else f"`{p}`",
                f"`{iri}`",
            )
            for p, iri in sorted(vocab.prefixes.items())
        ],
    )
    lines += [
        "## Machine-readable artifacts",
        "",
        "Served byte-identical at their canonical identifiers:",
        "",
    ]
    for path in artifact_files():
        rel = path.relative_to(_ARTIFACTS).as_posix()
        lines.append(f"- [`{rel}`]({origin}/{_SERVE_PREFIX}/{rel})")
    lines.append("")
    return "\n".join(lines)


def render_subnamespace_page(sub: Subnamespace, terms: list[Term]) -> str:
    """The Markdown source of one ``/vocab/<name>`` extension-namespace page.

    Its whole job is to make the IRIs this namespace's published data already
    carries dereference. Where the context enumerates terms in the namespace
    they render with a ``#`` anchor each (as on the core vocabulary page);
    where it does not — the usual case today, since these fields are minted
    per-particle by the extractor rather than declared in the core context —
    the page still resolves and says so.
    """
    lines = [
        _BANNER,
        "",
        f"# The `{sub.prefix}` extension vocabulary",
        "",
        f"Namespace IRI: `{sub.iri}`",
        "",
        "This is an **extension vocabulary** — a domain-specific namespace whose",
        "terms are minted and emitted by the extractor that produces this kind of",
        "particle, not declared by the core Particles schema. A serialized particle",
        f"names a term here as `{sub.prefix}:<term>`, which expands to",
        f"`{sub.iri}<term>` and dereferences to this page.",
        "",
        "The core vocabulary — the provenance, confidence, and lifecycle terms every",
        "particle carries — lives on the [Particles vocabulary](../vocab.md) page.",
        "This page exists so the identifiers this namespace's data already carries",
        "resolve to a real target.",
        "",
        "## Terms",
        "",
    ]
    if terms:
        lines += [
            "Each row is one term in this namespace and the JSON key (or keys) bound",
            "to it.",
            "",
        ]
        lines += _table(
            ("Term", "JSON key", "IRI"),
            [(_anchor(t.local), _keys(t), f"`{t.iri}`") for t in terms],
        )
    else:
        lines += [
            "The core context declares no terms in this namespace yet: its fields are",
            "attached per-particle by the extractor that emits them, not enumerated",
            "in the shared schema. As the standard gives these fields normative",
            "definitions they will be listed here, each with a `#`-fragment anchor.",
            "",
        ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# mkdocs hooks
# --------------------------------------------------------------------------- #
def on_pre_build(config: Any, **_kwargs: object) -> None:
    """Generate the vocabulary pages and check the artifacts' published identifiers."""
    check_schema_ids()
    vocab = parse_vocabulary(_load_context())
    origin = canonical_origin()

    _VOCAB_PAGE.parent.mkdir(parents=True, exist_ok=True)
    _VOCAB_PAGE.write_text(render_vocab_page(vocab, origin), encoding="utf-8")

    # One page per own-origin sub-namespace, served at the exact path its IRIs
    # dereference to. Regenerated wholesale each build: the directory holds only
    # generated files, so a prefix removed from the context leaves no stale page.
    if _VOCAB_SUBNS_DIR.exists():
        shutil.rmtree(_VOCAB_SUBNS_DIR)
    for sub in subnamespaces(vocab, origin):
        page = _VOCAB_SUBNS_DIR / Path(sub.doc_relpath).relative_to("vocab")
        page.parent.mkdir(parents=True, exist_ok=True)
        page.write_text(
            render_subnamespace_page(sub, _terms_for_prefix(vocab, sub.prefix)),
            encoding="utf-8",
        )


def on_post_build(config: Any, **_kwargs: object) -> None:
    """Copy the normative artifacts into the built site at their canonical paths."""
    site_dir = config["site_dir"] if isinstance(config, dict) else config.site_dir
    dst_root = Path(site_dir) / _SERVE_PREFIX
    for src in artifact_files():
        dst = dst_root / src.relative_to(_ARTIFACTS)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        if dst.read_bytes() != src.read_bytes():
            raise RuntimeError(f"artifact host: {dst} is not byte-identical to {src} after copy")
