# SPDX-FileCopyrightText: 2026 The Particles authors
#
# SPDX-License-Identifier: Apache-2.0

"""mkdocs build hook — bring the design system into the docs tree.

The docs site is skinned by the repo-wide design tokens (``design/tokens.css``,
see ``design/README.md``), but mkdocs only serves files under ``docs/``. Like
``copy_openapi.py`` for the OpenAPI snapshot, this hook materialises the
generated pieces at build time — every one of them gitignored, so ``design/``
stays the single source of truth:

* ``docs/stylesheets/tokens.css`` — ``design/tokens.css`` verbatim, followed by
  the same light / dark primitive blocks re-scoped under Material's own theme
  switch, ``body[data-md-color-scheme="default"|"slate"]``. Material stamps
  that attribute at parse time from its palette toggle, so the tokens follow
  the toggle with no JavaScript and no flash. The semantic layer is repeated
  inside each scope (see ``design/build.py: scoped_tokens``).
* ``docs/assets/favicon.svg`` — the app tile from ``design/``. (The header
  mark is ``overrides/.icons/particles/mark.svg``, a tracked copy this hook
  checks against ``design/logo-mark.svg`` — see ``_MARK_ICON`` below.)

The authored Material overrides live in ``docs/stylesheets/particles.css``
(tracked); they only reference ``--p-*`` variables.

Wired up via ``hooks:`` in ``mkdocs.yml``.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
_DESIGN = _REPO_ROOT / "design"
_DOCS = _REPO_ROOT / "docs"

_TOKENS_SRC = _DESIGN / "tokens.css"
_TOKENS_DST = _DOCS / "stylesheets" / "tokens.css"
_ASSETS = {
    _DESIGN / "logo-tile.svg": _DOCS / "assets" / "favicon.svg",
}
# The header mark is a Material custom *inline* icon (theme.icon.logo), so its
# currentColor core follows the header ink in both schemes — an <img> logo
# could not. Material needs the icon file inside `custom_dir` at config time
# (before any hook runs), so it is a tracked copy rather than a generated one;
# this hook fails the build if it drifts from the canonical mark.
_MARK_SRC = _DESIGN / "logo-mark.svg"
_MARK_ICON = _REPO_ROOT / "overrides" / ".icons" / "particles" / "mark.svg"

_MATERIAL_LIGHT = 'body[data-md-color-scheme="default"]'
_MATERIAL_DARK = 'body[data-md-color-scheme="slate"]'


def _material_scoped(tokens: str) -> str:
    # design/build.py is the token build tool; import its scoping helper rather
    # than re-implementing the block parser here.
    if str(_DESIGN) not in sys.path:
        sys.path.insert(0, str(_DESIGN))
    from build import scoped_tokens  # type: ignore[import-not-found]

    return scoped_tokens(tokens, _MATERIAL_LIGHT, _MATERIAL_DARK, with_semantic=True)


def on_pre_build(config: Any, **_kwargs: object) -> None:
    """Materialise tokens + brand assets into docs/ before mkdocs builds."""
    if not _TOKENS_SRC.exists():
        rel = _TOKENS_SRC.relative_to(_REPO_ROOT)
        raise FileNotFoundError(f"{rel} missing — the design system directory is gone?")
    tokens = _TOKENS_SRC.read_text()
    _TOKENS_DST.parent.mkdir(parents=True, exist_ok=True)
    _TOKENS_DST.write_text(
        tokens + "\n/* ---- Generated by hooks/copy_design_tokens.py: the same primitives under\n"
        "   Material's palette switch, so the tokens follow the site's toggle. ---- */\n"
        + _material_scoped(tokens)
    )
    for src, dst in _ASSETS.items():
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    if _MARK_ICON.read_bytes() != _MARK_SRC.read_bytes():
        raise RuntimeError(
            f"{_MARK_ICON.relative_to(_REPO_ROOT)} differs from "
            f"{_MARK_SRC.relative_to(_REPO_ROOT)} — run "
            f"`cp {_MARK_SRC.relative_to(_REPO_ROOT)} {_MARK_ICON.relative_to(_REPO_ROOT)}`."
        )
